### ISSUE TITLE
Preprocess in the kitti dataset

### ISSUE THREAD

**Issue by MugeTong** [liangheming/monodepth_v2#1]
Hello, I am reproducing this monodepth2 recently as well. Here are some puzzles that bother me.

1. How did you resolve the question when the default dataset format is ".jpg" not ".png"?
2. The repo has declared that it supposes all images are in the same intrinsic. How did you handle this for iamges of different dates?

**Comment by liangheming** [comment]
上述问题主要涉及 datasets/kitty.py中的__getitem__参数
针对问题1：读取图片使用的是 Image.open，这个函数只要传递文件路径即可，内部实现应该可以兼容不同文件后缀；
针对问题2：关注code_line: 224那一行开始的读取数据的逻辑，可以将内参和图像名对应存在一个map中，然后按需取用，具体实现逻辑需要自己实现，只能提供一个思路；

**Comment by MugeTong** [comment]
作者训练的时候都是用的一个摄像机内参吗？我不知道原作者怎么训练的，不过这样是不是不妥当？毕竟原有数据集每一部分的图像确实摄像机内参不一样
（你提到的这个想法确实能解决这个问题，我曾经也试过图像和参数一一对应，就像在SfMLearner中的那样，不知道这个参数对训练有没有影响）

另外，关于第一个问题我想说的是，原数据集的数据格式是png，但是这个原作者训练的时候都用的是jpg，这两张图像之间是只单单转换了一下（png->jpg）吗？🤔

**Comment by liangheming** [comment]
1、关于相机内参，这个repo所reference的那个应该是用的同一个相机内参，针对kitti数据集来说，这个数据集所用的设备，应该是一致的，只不过为了严谨，数据集在采集每一个sequence的时候，会进行标定，但是内参实际相差不大，故对模型精度影响不大；但是如果实际上相机内参彼此之间相差较大(经验上，同一个点的重投影误差超过5个像素的话)，的确需要考虑引入不同内参；

2、关于数据格式，原作者怎么做到不清楚，不过这个repo为了加速dataset的读取速度，为优先使用jpg，仅从工程实用角度来说，图像压缩(单纯地png转jpg)对模型所造成的影响不大（当然，此观点不适用与科研）

**Comment by liangheming** [comment]
比起MonoDepth 我更推荐 [SCDepth](https://github.com/liangheming/SCDepthV1)  仅供参考，毕竟这类工作从时间上来说其实比较老了

**Comment by MugeTong** [comment]
谢谢！

我了解过你提到的这篇论文，的确，这个在解决一致性问题上介绍了很多，我也正在学习这个。

再次感谢作者的耐心解答！
